// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgekk5L5bJuMvewGqsWWCKJO9uZfl62A',
    appId: '1:989163202865:web:6baa8fc1b21caa3b982810',
    messagingSenderId: '989163202865',
    projectId: 'fir-login-b18e7',
    authDomain: 'fir-login-b18e7.firebaseapp.com',
    storageBucket: 'fir-login-b18e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ukGMBgVejeosEwQtBI_b-bagEulnwt8',
    appId: '1:989163202865:android:5a9b7a94ee76490a982810',
    messagingSenderId: '989163202865',
    projectId: 'fir-login-b18e7',
    storageBucket: 'fir-login-b18e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWq05p5N7FsnpNPhU1yS4Hwhmws3Ou2Y8',
    appId: '1:989163202865:ios:68f0727d9ed5031f982810',
    messagingSenderId: '989163202865',
    projectId: 'fir-login-b18e7',
    storageBucket: 'fir-login-b18e7.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWq05p5N7FsnpNPhU1yS4Hwhmws3Ou2Y8',
    appId: '1:989163202865:ios:68f0727d9ed5031f982810',
    messagingSenderId: '989163202865',
    projectId: 'fir-login-b18e7',
    storageBucket: 'fir-login-b18e7.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgekk5L5bJuMvewGqsWWCKJO9uZfl62A',
    appId: '1:989163202865:web:fe2a07ec83b57a86982810',
    messagingSenderId: '989163202865',
    projectId: 'fir-login-b18e7',
    authDomain: 'fir-login-b18e7.firebaseapp.com',
    storageBucket: 'fir-login-b18e7.appspot.com',
  );
}
